### PR TITLE
Add resolver flag for correct dependency detection

### PR DESCRIPTION
**Pull request by chrissiwaffler**

### CODE REVIEW

**Comment by chrissiwaffler** [comment]
@microsoft-github-policy-service agree

**Comment by karthiknadig** [comment]
@chrissiwaffler Thanks for the PR. Sorry for the delayed review. Can you use python3.7 when generating the requirements?

**Comment by chrissiwaffler** [comment]
@karthiknadig unfortunately, I don't have access to Python3.7 right now
could you regenerate the hashes for it?

**Comment by karthiknadig** [comment]
Done

**Review by eleanorjboyd — APPROVED** [review]

**Review by anthonykim1 — APPROVED** [review]

**Pull request merged**
